services:
  psql:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=spv-notes
      - POSTGRES_PASSWORD=spv-notes
      - POSTGRES_DB=notes
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "notes"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      psql:
        condition: service_healthy
    env_file: ".env"
    entrypoint: >
      sh -c "until pg_isready -h psql -p 5432; do sleep 1; done &&
             npm run migrate up"

volumes:
  postgres:
